### ISSUE TITLE
Fails building with release 2.5

### ISSUE THREAD

**Issue by ralphrmartin** [Xilinx/PYNQ-Networking#18]
Has this project been abandoned? Under release 2.5, it fails to build numpy.

I dont understand even why its trying to do that as numpy is already installed...:

```
Building wheels for collected packages: kamene, netifaces, paho-mqtt, numpy
  Running setup.py bdist_wheel for kamene ... done
  Stored in directory: /root/.cache/pip/wheels/a3/50/a5/fe0378ed5275c6846a20dcf3efa21d9f64634bca3a4d3aefea
  Running setup.py bdist_wheel for netifaces ... done
  Stored in directory: /root/.cache/pip/wheels/23/8f/f3/7054578f04c904f70757c5c85a6e2823baa69d42365526e93d
  Running setup.py bdist_wheel for paho-mqtt ... done
  Stored in directory: /root/.cache/pip/wheels/02/94/6c/8474137cb7a5a3e001d70a22c8ff919caee69435376bccce79
  Running setup.py bdist_wheel for numpy ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-3fbfrchq/numpy/setup.py
';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))"
bdist_wheel -d /tmp/tmpkqq9nhw3pip-wheel- --python-tag cp36:
  Running from numpy source directory.
  Cythonizing sources
  Processing numpy/random/_bounded_integers.pxd.in
  Processing numpy/random/_common.pyx
  Traceback (most recent call last):
    File "/tmp/pip-build-3fbfrchq/numpy/tools/cythonize.py", line 238, in <module>
      main()
    File "/tmp/pip-build-3fbfrchq/numpy/tools/cythonize.py", line 234, in main
      find_process_files(root_dir)
    File "/tmp/pip-build-3fbfrchq/numpy/tools/cythonize.py", line 225, in find_process_files
      process(root_dir, fromfile, tofile, function, hash_db)
    File "/tmp/pip-build-3fbfrchq/numpy/tools/cythonize.py", line 191, in process
      processor_function(fromfile, tofile)
    File "/tmp/pip-build-3fbfrchq/numpy/tools/cythonize.py", line 79, in process_pyx
      VENDOR, required_version))
  RuntimeError: Building NumPy requires Cython >= 0.29.14
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-3fbfrchq/numpy/setup.py", line 488, in <module>
      setup_package()
    File "/tmp/pip-build-3fbfrchq/numpy/setup.py", line 469, in setup_package
      generate_cython()
    File "/tmp/pip-build-3fbfrchq/numpy/setup.py", line 275, in generate_cython
      raise RuntimeError("Running cythonize failed!")
  RuntimeError: Running cythonize failed!
```

**Comment by ralphrmartin** [comment]
I tried manually installing cython with "apt-get install cython" but that installed version 0.26.1-0.4
and I see that the error message above says "Building NumPy requires Cython >= 0.29.14".

Is there any straightforward way to proceed?

**Comment by ralphrmartin** [comment]
OK, the trick was to do 
pip3 install --upgrade Cython
first

**Comment by abunickabhi** [comment]
Thanks for the comment. The overlay fails to build in the v2.6 pynq image as well. It did not work with the cython installation. I will revert back to v2.4 OS just for this overlay addon.
